# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /csehome/dohbaek/HSD_2018_T1/hardware/hardware.srcs/sources_1/bd/design_2/ip/design_2_myip_0_0/design_2_myip_0_0.xci
# IP: The module: 'design_2_myip_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /csehome/dohbaek/HSD_2018_T1/hardware/hardware.srcs/sources_1/bd/design_2/ip/design_2_myip_0_0/src/clk_wiz_0_4/clk_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0}]

# IP: /csehome/dohbaek/HSD_2018_T1/hardware/hardware.srcs/sources_1/bd/design_2/ip/design_2_myip_0_0/src/floating_point_0/floating_point_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==floating_point_0 || ORIG_REF_NAME==floating_point_0}]

# XDC: /csehome/dohbaek/HSD_2018_T1/hardware/hardware.srcs/sources_1/bd/design_2/ip/design_2_myip_0_0/src/clk_wiz_0_4/clk_wiz_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0}] {/inst }]/inst ]]

# XDC: /csehome/dohbaek/HSD_2018_T1/hardware/hardware.srcs/sources_1/bd/design_2/ip/design_2_myip_0_0/src/clk_wiz_0_4/clk_wiz_0_ooc.xdc

# IP: /csehome/dohbaek/HSD_2018_T1/hardware/hardware.srcs/sources_1/bd/design_2/ip/design_2_myip_0_0/design_2_myip_0_0.xci
# IP: The module: 'design_2_myip_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /csehome/dohbaek/HSD_2018_T1/hardware/hardware.srcs/sources_1/bd/design_2/ip/design_2_myip_0_0/src/clk_wiz_0_4/clk_wiz_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0}]

# IP: /csehome/dohbaek/HSD_2018_T1/hardware/hardware.srcs/sources_1/bd/design_2/ip/design_2_myip_0_0/src/floating_point_0/floating_point_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==floating_point_0 || ORIG_REF_NAME==floating_point_0}]

# XDC: /csehome/dohbaek/HSD_2018_T1/hardware/hardware.srcs/sources_1/bd/design_2/ip/design_2_myip_0_0/src/clk_wiz_0_4/clk_wiz_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0}] {/inst }]/inst ]]

# XDC: /csehome/dohbaek/HSD_2018_T1/hardware/hardware.srcs/sources_1/bd/design_2/ip/design_2_myip_0_0/src/clk_wiz_0_4/clk_wiz_0_ooc.xdc
