# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /csehome/dohbaek/HSD_2018_T1/implementatio/implementatio.srcs/sources_1/bd/design_2/ip/design_2_rst_ps7_0_50M_0/design_2_rst_ps7_0_50M_0.xci
# IP: The module: 'design_2_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /csehome/dohbaek/HSD_2018_T1/implementatio/implementatio.srcs/sources_1/bd/design_2/ip/design_2_rst_ps7_0_50M_0/design_2_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /csehome/dohbaek/HSD_2018_T1/implementatio/implementatio.srcs/sources_1/bd/design_2/ip/design_2_rst_ps7_0_50M_0/design_2_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /csehome/dohbaek/HSD_2018_T1/implementatio/implementatio.srcs/sources_1/bd/design_2/ip/design_2_rst_ps7_0_50M_0/design_2_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /csehome/dohbaek/HSD_2018_T1/implementatio/implementatio.srcs/sources_1/bd/design_2/ip/design_2_rst_ps7_0_50M_0/design_2_rst_ps7_0_50M_0.xci
# IP: The module: 'design_2_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /csehome/dohbaek/HSD_2018_T1/implementatio/implementatio.srcs/sources_1/bd/design_2/ip/design_2_rst_ps7_0_50M_0/design_2_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /csehome/dohbaek/HSD_2018_T1/implementatio/implementatio.srcs/sources_1/bd/design_2/ip/design_2_rst_ps7_0_50M_0/design_2_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /csehome/dohbaek/HSD_2018_T1/implementatio/implementatio.srcs/sources_1/bd/design_2/ip/design_2_rst_ps7_0_50M_0/design_2_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
